### ISSUE TITLE
Adding header

### ISSUE THREAD

**Issue by DerekDahly** [gis4533-fall2020/duluth-poi-group-1#7]
Adding header to mapbox

**Comment by ghost** [comment]
Suggestion: This is the header I included in the Online Mapping Platform Project for this same scenario. We could use something similar...
<img width="1357" alt="Header Online Mapping Platform" src="https://user-images.githubusercontent.com/71836449/99090627-7b5cd100-2594-11eb-853f-da6f2cd22db2.png">
